# <div style="text-align: center; color: cyan">Loss function</div>


## <div style="text-align: center; color: lime">Setup</div>

In [2]:
import os

os.environ["KERAS_BACKEND"] = "torch"


## <div style="text-align: center; color: lime">Imports</div>


In [7]:
import torch

import numpy as np

import keras

> **Source**: https://keras.io/api/losses/


## <div style="text-align: center; color: lime">Binary CrossEntropy</div>

$$ \text{BCE}(y, \hat{y}) = - \left( y \log(\hat{y}) \;+\; (1 - y) \log(1 - \hat{y}) \right) $$


In [23]:
y_true = torch.Tensor([1, 0, 1, 0])
y_pred = torch.Tensor([0.2, 0.1, 0.9, 0.05])

keras.losses.binary_crossentropy(y_true, y_pred).cpu().numpy()

array(0.46786305, dtype=float32)

In [24]:
-(np.log(0.2) + np.log(0.9) + np.log(0.9) + np.log(0.95)) / 4

np.float64(0.4678630595343259)

In [26]:
bce = keras.losses.BinaryCrossentropy()

bce(y_true, y_pred).cpu().numpy()

array(0.46786305, dtype=float32)

## <div style="text-align: center; color: lime">Categorical CrossEntropy</div>

$$
\text{CCE}(y, \hat{y}) = - \sum_{k=1}^{K} y_k \log(\hat{y}_k)
$$

> Note: should be in on-hot format

In [28]:
# I have 4 classes and 3 data
y_true = torch.Tensor(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)

y_pred = torch.Tensor(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

keras.losses.categorical_crossentropy(y_true, y_pred).cpu().numpy()

array([0.22314352, 0.6931472 , 0.35667494], dtype=float32)

In [29]:
[-np.log(0.8), -np.log(0.5), -np.log(0.7)]

[np.float64(0.2231435513142097),
 np.float64(0.6931471805599453),
 np.float64(0.35667494393873245)]

In [30]:
cce = keras.losses.CategoricalCrossentropy(reduction=None)

cce(y_true, y_pred).cpu().numpy()

array([0.22314352, 0.6931472 , 0.35667494], dtype=float32)

## <div style="text-align: center; color: lime">Sparse Categorical CrossEntropy</div>

In [31]:
y_true = torch.Tensor(
    [
        0,
        1,
        3,
    ]
)
y_pred = torch.Tensor(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

keras.losses.sparse_categorical_crossentropy(y_true, y_pred).cpu().numpy()

array([0.22314352, 0.6931472 , 0.35667494], dtype=float32)

In [32]:
[-np.log(0.8), -np.log(0.5), -np.log(0.7)]

[np.float64(0.2231435513142097),
 np.float64(0.6931471805599453),
 np.float64(0.35667494393873245)]

In [34]:
scce = keras.losses.SparseCategoricalCrossentropy(reduction=None)

scce(y_true, y_pred).cpu().numpy()

array([0.22314352, 0.6931472 , 0.35667494], dtype=float32)

## <div style="text-align: center; color: lime">Custom loss function</div>

In [18]:
def custom_mae_loss(y_true, y_pred):
    return torch.mean(torch.abs(y_true - y_pred))

In [19]:
y_true = torch.Tensor(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)

y_pred = torch.Tensor(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

custom_mae_loss(y_true, y_pred).cpu().numpy()

array(0.16666667, dtype=float32)

In [21]:
class CustomMAELoss(keras.losses.Loss):
    def __init__(self):
        super().__init__()

    def call(self, y_true, y_pred):
        return torch.mean(torch.abs(y_true - y_pred))

In [22]:
y_true = torch.Tensor(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)

y_pred = torch.Tensor(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

al = CustomMAELoss()

al(y_true, y_pred).cpu().numpy()

array(0.16666667, dtype=float32)

<p style="text-align: center; font-family: "Trebuchet MS", sans-serif; color: #888; font-size: 0.9em; margin-top: 2em; border-top: 1px solid #ccc; padding-top: 0.5em;">
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</p>

<div style="text-align: center">
<a style="margin: 1em" href="https://literallytheone.github.io">https://literallytheone.github.io</a>
</div>
