# <div style="text-align: center; color: cyan">Average pooling layer</div>

## <div style="text-align: center; color: lime">Setup</div>

In [1]:
import os

os.environ["KERAS_BACKEND"] = "torch"

## <div style="text-align: center; color: lime">Imports</div>

In [2]:
from keras.layers import AveragePooling2D, GlobalAveragePooling2D

import numpy as np

## <div style="text-align: center; color: lime">Average Pooling</div>

In [3]:
a = np.arange(8, dtype=float).reshape(1, 2, 2, 2)

avg_pooing_layer = AveragePooling2D((2, 2), strides=1)

result = avg_pooing_layer(a).cpu().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


difference in shapes
(1, 2, 2, 2)
(1, 1, 1, 2)
--------------------
1st channel
[[0. 2.]
 [4. 6.]]
--------------------
second channel
[[1. 3.]
 [5. 7.]]
--------------------
result of the 1st channel
[[3.]]
--------------------
result of the 2nd channel
[[4.]]
--------------------


In [4]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

avg_pooing_layer = AveragePooling2D((2, 2), strides=1)

result = avg_pooing_layer(a).cpu().numpy()

print("differences in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


differences in shapes
(1, 4, 4, 2)
(1, 3, 3, 2)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
second channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result of the 1st channel
[[ 5.  7.  9.]
 [13. 15. 17.]
 [21. 23. 25.]]
--------------------
result of the 2nd channel
[[ 6.  8. 10.]
 [14. 16. 18.]
 [22. 24. 26.]]
--------------------


## <div style="text-align: center; color: lime">Global Average Pooling</div>

In [6]:
a = np.arange(8, dtype=float).reshape(1, 2, 2, 2)

avg_pooing_layer = GlobalAveragePooling2D()

result = avg_pooing_layer(a).cpu().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result")
print(result)
print("-" * 20)


difference in shapes
(1, 2, 2, 2)
(1, 2)
--------------------
1st channel
[[0. 2.]
 [4. 6.]]
--------------------
second channel
[[1. 3.]
 [5. 7.]]
--------------------
result
[[3. 4.]]
--------------------


In [7]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

avg_pooing_layer = GlobalAveragePooling2D()

result = avg_pooing_layer(a).cpu().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result")
print(result)
print("-" * 20)


difference in shapes
(1, 4, 4, 2)
(1, 2)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
second channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result
[[15. 16.]]
--------------------


<p style="text-align: center; font-family: "Trebuchet MS", sans-serif; color: #888; font-size: 0.9em; margin-top: 2em; border-top: 1px solid #ccc; padding-top: 0.5em;">
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</p>

<div style="text-align: center">
<a style="margin: 1em" href="https://literallytheone.github.io">https://literallytheone.github.io</a>
</div>
