# <div style="text-align: center; color: cyan">Convolutional layer</div>

## <div style="text-align: center; color: lime">Setup</div>

In [2]:
import os

os.environ["KERAS_BACKEND"] = "torch"

## <div style="text-align: center; color: lime">Imports</div>

In [3]:
import numpy as np

from keras.layers import Conv2D

## <div style="text-align: center; color: lime">Conv2D</div>

### <div style="text-align: center; color: lightsalmon">Normal example</div>

In [4]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = Conv2D(10, (2, 2))

result = conv_2d(a).cpu().detach().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("2nd channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


difference in shapes
(1, 4, 4, 2)
(1, 3, 3, 10)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
2nd channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result of the 1st channel
[[ 9.381765 12.033881 14.685997]
 [19.99023  22.642345 25.294462]
 [30.598694 33.250813 35.902927]]
--------------------
result of the 2nd channel
[[ 2.9300334  3.7793055  4.628578 ]
 [ 6.3271227  7.1763954  8.025667 ]
 [ 9.724212  10.573485  11.422758 ]]
--------------------


### <div style="text-align: center; color: lightsalmon">Strides example</div>

In [5]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = Conv2D(10, (2, 2), strides=(2, 1))

result = conv_2d(a).cpu().detach().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

difference in shapes
(1, 4, 4, 2)
(1, 2, 3, 10)
--------------------


### <div style="text-align: center; color: lightsalmon">Padding example</div>

In [6]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = Conv2D(10, (2, 2), padding="same")

result = conv_2d(a).cpu().detach().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

difference in shapes
(1, 4, 4, 2)
(1, 4, 4, 10)
--------------------


### <div style="text-align: center; color: lightsalmon">Dilation</div>

In [8]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = Conv2D(
    filters=10,
    kernel_size=(2, 2),
    dilation_rate=(2, 2),
)

result = conv_2d(a).cpu().detach().numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)


difference in shapes
(1, 4, 4, 2)
(1, 2, 2, 10)
--------------------


<p style="text-align: center; font-family: "Trebuchet MS", sans-serif; color: #888; font-size: 0.9em; margin-top: 2em; border-top: 1px solid #ccc; padding-top: 0.5em;">
    @LiterallyTheOne — PhD Candidate in Artificial Intelligence
</p>

<div style="text-align: center">
<a style="margin: 1em" href="https://literallytheone.github.io">https://literallytheone.github.io</a>
</div>
